# Source data for the starter-prompt catalog. Text after "|" inside [[...|...]] is the no-context fallback.
# Tuple form for prompts: (text, category). Categories: Discover, Analyze, Investigate, Decide, Prepare, Act, Monitor.
A = "[[{account}|this account]]"
CAPS = [
dict(id="account", name="Account Intelligence", skill="account-intelligence-swot-planning", intent="account_strategy", slash="account", domain="Accounts",
 description="Understand an account end to end: strategy, changes, opportunities, risks and relationships.",
 primary=[("Build my complete [[{account} ]]account strategy.", "Prepare"), (f"What has changed in {A}?", "Monitor"), ("Show me the biggest growth opportunities[[ in {account}]].", "Discover"),
          (f"Identify the major risks in {A}.", "Investigate"), ("Map the key stakeholders and relationships[[ at {account}]].", "Discover", "relationships"), (f"Give me an executive briefing on {A}.", "Prepare")],
 additional=[("Show me the account's current business priorities.", "Discover"), (f"Build a SWOT for {A}.", "Analyze"), ("Where do we have whitespace[[ in {account}]]?", "Discover"),
             ("What should I focus on this quarter?", "Decide"), (f"What are we missing in {A}?", "Investigate"), ("Compare our footprint with the customer's priorities.", "Analyze"),
             ("Show me our strategic position[[ in {account}]].", "Analyze"), ("What should I discuss with the executive sponsor?", "Prepare"), ("Show me the account history[[ for {account}]].", "Discover"),
             ("What changed since my last account review?", "Monitor")],
 follow=["Find the biggest opportunity[[ in {account}]].", "Show me competitive threads[[ in {account}]].", "Map the buying committee.", "Create a 90-day action plan.", "Prepare me for the next executive meeting."],
 outcomes=["A 12-section account plan with evidence behind every conclusion", "What changed since the last snapshot, by domain"],
 personas={"ceo": ["Show me the strategic position of [[{account}|our key accounts]].", "Where can [[{account}|this account]] grow fastest?"], "ae": ["What should I do next in [[{account}|this account]]?"]}),
dict(id="account-plan", name="Account Planning & SWOT", skill="account-intelligence-swot-planning", intent="account_strategy", slash="account-plan", domain="Accounts",
 description="Build an evidence-backed account plan, SWOT and plays.",
 primary=[("Build my[[ {account}]] account plan.", "Prepare"), ("Create an evidence-backed SWOT[[ for {account}]].", "Analyze"), ("Identify expansion plays for my account plan.", "Discover"),
          ("Identify account risks[[ in {account}]].", "Investigate"), ("Show me whitespace[[ in {account}]].", "Discover"), ("Recommend my account plays.", "Decide")],
 additional=[("What are the customer's strategic priorities?", "Discover"), ("Where are we underpenetrated?", "Analyze"), ("What should I do next[[ in {account}]]?", "Act"),
             ("Which stakeholders should I engage?", "Act"), ("What could prevent expansion?", "Investigate"), ("Show me the competitive implications.", "Analyze"), ("Build a 90-day account plan.", "Prepare"),
             ("Turn the plan into actions with owners.", "Act"), ("Show me the evidence behind the plan.", "Investigate"), ("Compare this plan with last quarter's.", "Monitor")],
 follow=["Build a 90-day account plan.", "Turn the plan into actions with owners.", "Map the buying committee.", "Show me the evidence behind the plan."],
 outcomes=["An account plan with SWOT, whitespace and plays", "A 90-day plan with owners"], personas={"sales_director": ["Review the account plans that need my input."]}),
dict(id="opportunities", name="Growth Opportunities", skill="growth-opportunity-discovery", intent="opportunity_discovery", slash="opportunities", domain="Growth",
 description="Find, explain and prioritize where to grow.",
 primary=[("Find my biggest growth opportunities[[ in {account}]].", "Discover"), ("Find whitespace[[ in {account}]].", "Discover"), ("Identify expansion opportunities[[ in {account}]].", "Discover"),
          ("Find competitive displacement opportunities.", "Discover"), ("Show me why these opportunities matter.", "Investigate"), ("Prioritize my opportunities.", "Decide")],
 additional=[("Find opportunities we are currently missing.", "Discover"), ("Which opportunities have the strongest buying signals?", "Analyze"), ("Which accounts are warming?", "Monitor"),
             ("Where should I focus first?", "Decide"), ("Find cross-sell opportunities.", "Discover"), ("Find upsell opportunities.", "Discover"), ("Find transformation opportunities.", "Discover"),
             ("Find opportunities driven by customer investment.", "Investigate"), ("Find opportunities driven by competitive activity.", "Investigate"), ("Size the top opportunity with evidence.", "Analyze")],
 follow=["Build a plan for the top opportunity.", "Map the stakeholders for this opportunity.", "Show me the competitive context.", "Model the impact of winning this opportunity."],
 outcomes=["Opportunities with why-now, evidence, value range or 'unsized', and next action"], personas={"ceo": ["Where is our biggest untapped growth?"], "growth_ops": ["Where is growth potential concentrated?"]}),
dict(id="deal", name="Deal Strategy", skill="deal-intelligence", intent="deal_analysis", slash="deal", domain="Sales",
 description="Assess a deal, find what could stop it, and plan the win.",
 primary=[("Assess the health of [[{opportunity}|this deal]].", "Analyze"), ("Tell me what could prevent us from winning.", "Investigate"), ("Build my deal strategy[[ for {opportunity}]].", "Prepare"),
          ("Identify the missing stakeholders[[ in {opportunity}]].", "Investigate"), ("Show me the competitive risks in [[{opportunity}|this deal]].", "Investigate"), ("Tell me what I should do next on this deal.", "Act")],
 additional=[("What is the customer's likely decision process?", "Analyze"), ("What objections should I expect?", "Prepare"), ("Where is this deal stuck?", "Investigate"),
             ("What evidence supports the deal forecast?", "Investigate"), ("What could change the outcome?", "Analyze"), ("Prepare my executive strategy for this deal.", "Prepare"), ("Create a deal review.", "Prepare"),
             ("Show me deal momentum.", "Monitor"), ("Build a close plan with dates.", "Act"), ("Which of my deals will slip?", "Monitor")],
 follow=["Build a close plan with dates.", "Map the buying committee.", "Prepare my executive strategy for this deal.", "Analyze the pricing for this deal."],
 outcomes=["Deal health, win probability and slip risk with evidence", "A dated close plan"], personas={"sales_director": ["Show me which deals need intervention."], "ae": ["What should I do next on [[{opportunity}|this deal]]?"]}),
dict(id="forecast", name="Pipeline & Forecast", skill="pipeline-forecast-intelligence", intent="pipeline_forecast", slash="forecast", aliases=["pipeline"], domain="Sales",
 description="Review pipeline health, build the forecast and stress-test it.",
 primary=[("Review my pipeline for risks and next steps.", "Analyze"), ("Build my sales forecast.", "Prepare"), ("Show me pipeline coverage.", "Analyze"), ("Identify stalled opportunities.", "Investigate"),
          ("Show me forecast risks.", "Investigate"), ("Run forecast scenarios.", "Decide")],
 additional=[("Which deals need intervention?", "Act"), ("Where is pipeline weakening?", "Monitor"), ("Show me pipeline by region.", "Analyze"), ("Show me pipeline by rep.", "Analyze"),
             ("Show me pipeline by stage.", "Analyze"), ("What changed since the last forecast?", "Monitor"), ("What happens if these three deals slip?", "Decide"), ("Build best, base and worst-case scenarios.", "Decide"),
             ("Identify deals likely to slip.", "Investigate"), ("Explain the forecast.", "Analyze"), ("Show me coverage gaps.", "Analyze"), ("Forecast my pipeline.", "Prepare")],
 follow=["Which deals need intervention?", "What happens if these three deals slip?", "Show me coverage gaps.", "Prepare the forecast call."],
 outcomes=["A P10/P50/P90 forecast range with the deals that drive it", "Coverage and slippage by segment"], personas={"cro": ["Will we hit the number this quarter?"], "sales_director": ["Show me which deals need intervention."], "cfo": ["How reliable is this quarter's forecast?"]}),
dict(id="meeting", name="Meeting Preparation", skill="meeting-intelligence-brief", intent="meeting_prep", slash="meeting", domain="Meetings",
 description="Walk into any customer meeting prepared.",
 primary=[("Prep me for my next sales call.", "Prepare"), ("Give me a pre-meeting executive briefing.", "Prepare"), ("Show me what I need to know before [[{meeting}|this meeting]].", "Prepare"),
          ("Identify the customer's priorities.", "Discover"), ("Tell me what questions I should ask.", "Prepare"), ("Prepare my meeting strategy.", "Prepare")],
 additional=[("What changed since our last meeting?", "Monitor"), ("What should I avoid discussing?", "Prepare"), ("What are the likely objections?", "Prepare"), ("Who will attend and what matters to them?", "Discover"),
             ("What competitive issues should I be ready for?", "Investigate"), ("Give me a 5-minute briefing.", "Prepare"), ("What commitments do we owe them?", "Investigate"), ("Draft an agenda for the meeting.", "Act"),
             ("Prepare me for the CIO meeting.", "Prepare"), ("Which risks should I raise?", "Decide")],
 follow=["Draft an agenda for the meeting.", "What are the likely objections?", "Process my call notes into follow-ups."],
 outcomes=["A one-page brief: objectives, attendees, what changed, landmines, questions"], personas={"ae": ["Prep me for my next sales call."], "ceo": ["Brief me before my executive meeting[[ with {account}]]."]}),
dict(id="followup", name="Meeting Follow-through", skill="meeting-follow-through", intent="meeting_followup", slash="followup", domain="Meetings",
 description="Turn a meeting into follow-ups, updates and commitments.",
 primary=[("Process my call notes into follow-ups.", "Act"), ("Extract decisions and actions from the meeting.", "Analyze"), ("Create follow-up tasks from the meeting.", "Act"), ("Identify commitments made in the meeting.", "Investigate"),
          ("Update the account intelligence from the meeting.", "Act"), ("Update the opportunity based on this meeting.", "Act")],
 additional=[("Draft the follow-up email.", "Act"), ("Identify unanswered questions from the meeting.", "Investigate"), ("Identify new opportunities from the meeting.", "Discover"), ("Identify risks raised in the meeting.", "Investigate"),
             ("Update stakeholder relationships from the meeting.", "Act"), ("Update competitive intelligence from the meeting.", "Act"), ("Summarize the meeting for my manager.", "Prepare"), ("Log my meeting.", "Act"),
             ("Compare what was agreed with the opportunity record.", "Analyze"), ("Show me open commitments across my meetings.", "Monitor")],
 follow=["Draft the follow-up email.", "Update the opportunity based on this meeting.", "Show me open commitments across my meetings."],
 outcomes=["An approval-ready CRM update, recap draft and commitments list"], personas={}),
dict(id="relationships", name="Relationships", skill="relationship-intelligence", intent="relationships", slash="relationships", domain="Customers",
 description="See who matters, who is engaged and where access is at risk.",
 primary=[("Map the key stakeholders[[ at {account}]].", "Discover"), ("Show me relationship risks[[ at {account}]].", "Investigate"), ("Identify my strongest relationships.", "Analyze"), ("Show me executive engagement[[ at {account}]].", "Analyze"),
          ("Identify missing relationships[[ at {account}]].", "Investigate"), ("Tell me who I should engage next.", "Act")],
 additional=[("Who is my champion[[ at {account}]]?", "Discover"), ("Who has influence over the decision?", "Analyze"), ("Where are we losing access?", "Monitor"), ("Which relationships are weakening?", "Monitor"),
             ("Who can introduce me to the CIO?", "Act"), ("Show me the buying committee.", "Discover"), ("Are we single-threaded anywhere?", "Investigate"), ("Where do we need executive sponsorship?", "Decide"),
             ("Show me relationship trends over time.", "Monitor"), ("Build a plan to re-engage a weakening champion.", "Act")],
 follow=["Build a plan to re-engage a weakening champion.", "Who can introduce me to the CIO?", "Prepare me for my next sales call."],
 outcomes=["A stakeholder map with influence, strength, trend and gaps"], personas={"sales_director": ["Where are my teams single-threaded?"]}),
dict(id="customer-growth", name="Customer Growth", skill="renewal-expansion-radar", intent="customer_health", slash="customer-growth", domain="Customers",
 description="Grow existing customers: expansion, adoption and health.",
 primary=[("Find expansion opportunities with existing customers.", "Discover"), ("Identify customer growth signals.", "Discover"), ("Show me adoption changes.", "Monitor"), ("Identify renewal risks.", "Investigate"),
          ("Find whitespace in our customer base.", "Discover"), ("Build a customer growth plan[[ for {account}]].", "Prepare")],
 additional=[("Which products should we expand?", "Decide"), ("Where is adoption increasing?", "Analyze"), ("Where is adoption declining?", "Monitor"), ("Which customers are ready to expand?", "Discover"),
             ("What is driving customer growth?", "Investigate"), ("What should customer success focus on?", "Decide"), ("Show me customer health[[ for {account}]].", "Analyze"), ("Which customers need attention this month?", "Act"),
             ("Compare health across my customers.", "Analyze"), ("What changed in customer health?", "Monitor")],
 follow=["Build my renewal strategy.", "Which customers need attention this month?", "Prioritize my opportunities."],
 outcomes=["Customer health with drivers, expansion propensity and a play per account"], personas={"cs_leader": ["Which customers need attention this month?", "Where is adoption declining?"]}),
dict(id="renewals", name="Renewals & Expansion", skill="renewal-expansion-radar", intent="customer_health", slash="renewals", domain="Customers",
 description="Protect renewals and find expansion-ready accounts.",
 primary=[("Show me accounts at renewal risk.", "Investigate"), ("Identify expansion-ready accounts.", "Discover"), ("Find churn signals.", "Investigate"), ("Show me renewal drivers.", "Analyze"),
          ("Identify customer health changes.", "Monitor"), ("Build my renewal strategy[[ for {account}]].", "Prepare")],
 additional=[("Which renewals need executive intervention?", "Act"), ("What changed since the last renewal review?", "Monitor"), ("Which customers have expansion potential?", "Discover"), ("Which competitors are involved in renewals?", "Investigate"),
             ("What are the commercial risks in renewals?", "Investigate"), ("Predict churn for the next two quarters.", "Analyze"), ("Show me renewals due in the next six months.", "Monitor"), ("Prepare a renewal review.", "Prepare"),
             ("Model the impact of losing this customer.", "Decide"), ("What would save this renewal?", "Decide")],
 follow=["Which renewals need executive intervention?", "Model the impact of losing this customer.", "Prepare a renewal review."],
 outcomes=["Renewal risk and expansion upside 6–9 months ahead, with a recommended play"], personas={"cs_leader": ["Show me accounts at renewal risk."], "cfo": ["How much revenue is at renewal risk?"]}),
dict(id="competition", name="Competitive Intelligence", skill="competitive-intelligence", intent="competitive", slash="competition", domain="Competition",
 description="See the competitive landscape and where it threatens or helps us.",
 primary=[("Show me the competitive landscape[[ in {account}]].", "Discover"), ("Identify competitive threats[[ in {account}]].", "Investigate"), ("Show me where competitors are gaining ground.", "Monitor"),
          ("Find where we can displace competitors.", "Discover"), ("Analyze [[{competitor}|this competitor]].", "Analyze"), ("Show me recent competitive signals.", "Monitor")],
 additional=[("What is [[{competitor}|this competitor]] doing in my accounts?", "Investigate"), ("Where is [[{competitor}|this competitor]] appearing in opportunities?", "Investigate"), ("Which accounts are most exposed to competitors?", "Analyze"),
             ("What competitive patterns are emerging?", "Monitor"), ("Show me competitor pricing signals.", "Investigate"), ("What should I do about [[{competitor}|this competitor]]?", "Decide"), ("Build a battlecard for [[{competitor}|this competitor]].", "Prepare"),
             ("Who are we losing to?", "Analyze"), ("Compare our win rate against each competitor.", "Analyze"), ("Show me emerging competitors.", "Monitor")],
 follow=["Show me active competitive threads.", "Build a battlecard for [[{competitor}|this competitor]].", "Prepare a competitive response."],
 outcomes=["Competitor footprint, threat and momentum, with early warnings"], personas={"ceo": ["Where are competitors gaining ground?"], "marketing_leader": ["Which competitor content is getting attention?"]}),
dict(id="threads", name="Competitive Threads", skill="competitive-thread-intelligence", intent="competitive_ground", slash="threads", domain="Competition",
 description="Follow each competitive situation as one evolving story.",
 primary=[("Show me active competitive threads.", "Monitor"), ("Which competitive threads are accelerating?", "Monitor"), ("Explain [[the {competitor} thread|this competitive thread]].", "Investigate"),
          ("Show me the evidence behind [[the {competitor} threat|this threat]].", "Investigate"), ("Predict what [[{competitor}|this competitor]] could do next.", "Analyze"), ("What should I do about [[the {competitor} threat|this threat]]?", "Decide")],
 additional=[("When did [[the {competitor} thread|this thread]] start?", "Investigate"), ("What signals made [[the {competitor} thread|this thread]] accelerate?", "Investigate"), ("Show me counter-evidence for [[the {competitor} threat|this threat]].", "Investigate"),
             ("Which opportunities does [[{competitor}|this thread]] affect?", "Analyze"), ("Which stakeholders are involved in [[the {competitor} thread|this thread]]?", "Discover"), ("Has this kind of threat happened before?", "Investigate"),
             ("What happened in similar competitive situations?", "Investigate"), ("Record the outcome of this competitive thread.", "Act"), ("Show me weakening competitive threads.", "Monitor"), ("Prepare a competitive response.", "Prepare")],
 follow=["Prepare a competitive response.", "Which opportunities does [[{competitor}|this thread]] affect?", "Show me counter-evidence for [[the {competitor} threat|this threat]]."],
 outcomes=["A thread timeline with velocity, momentum, counter-evidence, predicted next event and actions"], personas={"ae": ["Which competitors are active in my deals?"]}),
dict(id="market", name="Market Intelligence", skill="market-intelligence", intent="market_view", slash="market", domain="Market",
 description="Understand the market, its trends and how they affect us.",
 primary=[("What's changing in this market?", "Monitor"), ("Show me the major market trends.", "Discover"), ("Identify growth opportunities from market changes.", "Discover"), ("Show me emerging market threats.", "Investigate"),
          ("Analyze [[the {industry}|this]] industry.", "Analyze"), ("Tell me what I should be watching in the market.", "Monitor")],
 additional=[("What market changes affect [[{account}|this account]]?", "Investigate"), ("Which market trends could create demand?", "Discover"), ("Which market trends could reduce demand?", "Investigate"), ("What are competitors doing in the market?", "Monitor"),
             ("Which technologies are changing the market?", "Discover"), ("Show me market investment trends.", "Analyze"), ("How do we compare with market benchmarks?", "Analyze"), ("Is our growth good for this market?", "Analyze"),
             ("Show me regulatory changes that matter.", "Monitor"), ("Summarize the market for my board.", "Prepare")],
 follow=["How do we compare with market benchmarks?", "Identify growth opportunities from market changes.", "Summarize the market for my board."],
 outcomes=["Source-attributed market context tied to our KPIs and accounts"], personas={"investor": ["How does the company compare with its market?"], "it_leader": ["Which technologies are changing our market?"]}),
dict(id="financial", name="Financial Intelligence", skill="financial-intelligence", intent="financial_story", slash="financial", domain="Finance",
 description="Tell the financial story and what it means commercially.",
 primary=[("Show me the financial story[[ for {account}]].", "Discover"), ("Analyze the last five years of financials.", "Analyze"), ("What financial changes matter?", "Investigate"), ("Show me margin and profitability trends.", "Analyze"),
          ("Find financial signals that could create opportunities.", "Discover"), ("Explain the financial position[[ of {account}]].", "Analyze")],
 additional=[("Show me revenue growth.", "Analyze"), ("Analyze EBITDA.", "Analyze"), ("Show me cash-flow trends.", "Analyze"), ("Where is the company investing?", "Discover"), ("Where is the company under financial pressure?", "Investigate"),
             ("What do the financials mean commercially?", "Decide"), ("Show me business-unit performance.", "Analyze"), ("Compare current performance with prior years.", "Analyze"), ("Show me capex and technology investment.", "Analyze"),
             ("Which financial figures are missing or estimated?", "Investigate")],
 follow=["What do the financials mean commercially?", "Find financial signals that could create opportunities.", "Show me margin and profitability trends."],
 outcomes=["Cited metrics computed in code, missing values named, signals and commercial implications"], personas={"investor": ["Show me the company's growth, profitability and strategic risks."], "cfo": ["Explain the margin trend and its drivers."]}),
dict(id="marketing", name="Marketing Intelligence", skill="marketing-intelligence", intent="marketing_view", slash="marketing", domain="Marketing",
 description="Turn marketing activity into account intelligence.",
 primary=[("Show me marketing activity affecting [[{account}|this account]].", "Discover"), ("Identify accounts showing buying intent.", "Discover"), ("Show me marketing engagement trends.", "Monitor"), ("Which campaigns are influencing pipeline?", "Analyze"),
          ("Which accounts are warming?", "Monitor"), ("Show me marketing-to-revenue signals.", "Analyze")],
 additional=[("Which executives are engaging with our marketing?", "Discover"), ("Which campaigns influence opportunities?", "Analyze"), ("Show me ABM performance.", "Analyze"), ("Which accounts are cooling?", "Monitor"),
             ("Find marketing signals sales should act on.", "Act"), ("Which competitor-related content is getting attention?", "Investigate"), ("Is campaign influence correlation or causation?", "Investigate"), ("Show me intent surges this month.", "Monitor"),
             ("Where is marketing creating pipeline?", "Analyze"), ("Show me the marketing timeline[[ for {account}]].", "Discover")],
 follow=["Find marketing signals sales should act on.", "Which accounts are cooling?", "Find my biggest growth opportunities[[ in {account}]]."],
 outcomes=["Engagement change, executive engagement, intent and campaign influence labelled as correlation"], personas={"marketing_leader": ["Which campaigns are influencing pipeline?", "Show me ABM performance."]}),
dict(id="pricing", name="Pricing", skill="pricing-intelligence", intent="pricing", slash="pricing", domain="Finance",
 description="Price deals with evidence; approvals stay governed.",
 primary=[("Analyze the pricing for this deal.", "Analyze"), ("Should we change the commercial structure?", "Decide"), ("Show me pricing benchmarks.", "Discover"), ("Analyze the discount on this deal.", "Analyze"),
          ("Model pricing scenarios.", "Decide"), ("Show me the margin impact of this price.", "Analyze")],
 additional=[("What happens with a 10% discount?", "Decide"), ("What is our historical pricing for similar deals?", "Discover"), ("How does this price compare with similar deals?", "Analyze"), ("Show me price sensitivity.", "Analyze"),
             ("Build a commercial scenario.", "Decide"), ("Will this discount need approval?", "Investigate"), ("Where are we leaking discount?", "Investigate"), ("Draft the discount approval justification.", "Act"),
             ("Check my quote against guardrails.", "Investigate"), ("Show me expected value by discount level.", "Analyze")],
 follow=["Will this discount need approval?", "Draft the discount approval justification.", "Show me the margin impact of this price."],
 outcomes=["Price → discount → margin → win probability, with approval route; no commitment without approval"], personas={"cfo": ["Where are we leaking discount?"]}),
dict(id="scenario", name="Scenario Planning", skill="scenario-planner", intent="scenario", slash="scenario", domain="Decisions",
 description="Model what-ifs before committing.",
 primary=[("Run a best, base and worst-case scenario.", "Decide"), ("What happens if this deal slips?", "Decide"), ("Model the impact of losing this customer.", "Decide"), ("Model the impact of winning this opportunity.", "Decide"),
          ("Compare strategic scenarios.", "Decide"), ("Show me the financial impact of this scenario.", "Analyze")],
 additional=[("What happens if win rate drops five points?", "Decide"), ("How many reps do we need to hit the number?", "Decide"), ("Model a price increase.", "Decide"), ("Which assumptions matter most?", "Investigate"),
             ("What is the gap to target?", "Analyze"), ("Build a capacity plan.", "Prepare"), ("What if pipeline creation slows?", "Decide"), ("Stress-test next year's plan.", "Decide"), ("Show me the assumptions behind this scenario.", "Investigate"),
             ("What would close the gap to target?", "Decide")],
 follow=["Which assumptions matter most?", "Prepare an executive decision brief.", "What would close the gap to target?"],
 outcomes=["Best/base/worst cases with sensitivity and the gap to target, labelled as modeled"], personas={"cfo": ["Stress-test next year's plan."], "coo": ["Build a capacity plan."]}),
dict(id="decision", name="Decision Support", skill="decision-intelligence", intent="decision", slash="decision", domain="Decisions",
 description="Evaluate options, trade-offs and evidence before deciding.",
 primary=[("Help me evaluate this decision.", "Decide"), ("Show me the options and trade-offs.", "Decide"), ("What evidence supports each option?", "Investigate"), ("What are the risks of each option?", "Investigate"),
          ("Run a scenario analysis for this decision.", "Decide"), ("Prepare an executive decision brief.", "Prepare")],
 additional=[("What information am I missing for this decision?", "Investigate"), ("What assumptions are we making?", "Investigate"), ("What could change this decision?", "Analyze"), ("Show me the downside of this decision.", "Investigate"),
             ("Show me the expected impact of each option.", "Analyze"), ("What should we monitor after the decision?", "Monitor"), ("Challenge your recommendation.", "Decide"), ("What did we decide previously?", "Discover"),
             ("Record this decision.", "Act"), ("Who needs to approve this decision?", "Act")],
 follow=["Challenge your recommendation.", "Record this decision.", "What should we monitor after the decision?"],
 outcomes=["Options including status quo, evidence, trade-offs, recommendation, confidence and owner"], personas={"ceo": ["What decisions need my attention?"]}),
dict(id="executive", name="Executive Command Center", skill="executive-command-center", intent="business_health", slash="executive", domain="Growth",
 description="The state of the business at executive altitude.",
 primary=[("Give me the state of the business.", "Analyze"), ("What changed materially?", "Monitor"), ("Show me the biggest opportunities.", "Discover"), ("Show me the biggest risks.", "Investigate"),
          ("What should leadership focus on?", "Decide"), ("Give me an executive briefing.", "Prepare")],
 additional=[("What should concern me?", "Investigate"), ("Where is growth accelerating?", "Analyze"), ("Where is growth weakening?", "Monitor"), ("What requires executive intervention?", "Act"), ("What are the top strategic signals?", "Monitor"),
             ("How are we doing against plan?", "Analyze"), ("Prepare my board update.", "Prepare"), ("Show me the investor view.", "Analyze"), ("Which KPIs moved most this month?", "Monitor"), ("What did we forecast last time, and what happened?", "Investigate")],
 follow=["What requires executive intervention?", "Prepare my board update.", "Help me evaluate this decision."],
 outcomes=["How we are doing, what changed, why, what next and what to do, per KPI with confidence"], personas={"ceo": ["Show me the biggest growth and risk signals."], "investor": ["Show me the company's growth, profitability and strategic risks."], "coo": ["What operational risks need attention?"]}),
dict(id="bi", name="Business Analysis", skill="business-intelligence-copilot", intent="cross_functional", slash="bi", domain="Growth",
 description="Ask why any business number moved.",
 primary=[("Analyze my business.", "Analyze"), ("What should I know today?", "Monitor"), ("What changed in the business?", "Monitor"), ("Find unusual patterns in the business.", "Investigate"),
          ("Show me the most important signals.", "Monitor"), ("Tell me what needs attention.", "Act")],
 additional=[("Why is a region behind plan?", "Investigate"), ("What is driving the drop in retention?", "Investigate"), ("Why did margin fall last quarter?", "Investigate"), ("Where is the gap to plan?", "Analyze"),
             ("Explain this number.", "Investigate"), ("Which drivers matter most?", "Analyze"), ("Compare segments over time.", "Analyze"), ("What happened, and why?", "Investigate"), ("Break down revenue variance.", "Analyze"),
             ("What is likely to happen next?", "Analyze")],
 follow=["Which drivers matter most?", "Run a best, base and worst-case scenario.", "Tell me what needs attention."],
 outcomes=["What happened, why, key drivers, what is likely, what to do, with evidence"], personas={"coo": ["Where are operations slowing growth?"]}),
dict(id="signals", name="Growth Signals", skill="growth-signal-orchestrator", intent="signals", slash="signals", domain="Growth",
 description="Connect signals across functions into growth and risk patterns.",
 primary=[("Show me the strongest growth signals.", "Monitor"), ("Find emerging opportunities across my accounts.", "Discover"), ("Find compound signals across my accounts.", "Investigate"), ("Show me accounts becoming more attractive.", "Monitor"),
          ("Show me accounts becoming risky.", "Monitor"), ("Explain why this signal matters.", "Investigate")],
 additional=[("Connect the dots across my accounts.", "Investigate"), ("Which customers are at risk, and why?", "Investigate"), ("Where are expansion signals aligning?", "Discover"), ("Show me signals from three or more domains.", "Investigate"),
             ("Which signals should sales act on?", "Act"), ("Which signals are weakening?", "Monitor"), ("Show me the evidence chain for this pattern.", "Investigate"), ("Show me margin-erosion signals.", "Monitor"),
             ("Show me executive-access loss signals.", "Monitor"), ("Route this signal to the right owner.", "Act")],
 follow=["Show me the evidence chain for this pattern.", "Route this signal to the right owner.", "Find my biggest growth opportunities[[ in {account}]]."],
 outcomes=["Cross-domain patterns (detected or emerging) with evidence, confidence and owner"], personas={"growth_ops": ["Find compound signals across my accounts."]}),
dict(id="briefing", name="Daily Briefing", skill="daily-growth-briefing", intent="briefing", slash="briefing", domain="Growth",
 description="Your personalized start-of-day briefing.",
 primary=[("Give me today's growth briefing.", "Monitor"), ("What changed overnight?", "Monitor"), ("What needs my attention today?", "Act"), ("Show me today's opportunities.", "Discover"), ("Show me today's risks.", "Investigate"),
          ("Give me my top priorities for today.", "Decide")],
 additional=[("Catch me up on my accounts.", "Monitor"), ("Which deals moved yesterday?", "Monitor"), ("Any new competitive signals today?", "Monitor"), ("Which renewals need attention this week?", "Act"), ("What did my team close yesterday?", "Monitor"),
             ("Set up my daily briefing.", "Act"), ("What should I prepare for tomorrow?", "Prepare"), ("Summarize this week so far.", "Monitor"), ("Anything I should know before my meetings?", "Prepare"), ("Which actions are due today?", "Act")],
 follow=["Which actions are due today?", "Prep me for my next sales call.", "Show me what changed[[ in {account}]]."],
 outcomes=["Ranked changes for your role: what changed, why it matters, what to do"], personas={"ae": ["What needs my attention today?"], "sales_head": ["Catch me up on my team's deals."]}),
dict(id="actions", name="Actions", skill="action-center", intent="action", slash="actions", domain="Operations",
 description="See, prioritize and execute actions with approval.",
 primary=[("Show me my highest-priority actions.", "Act"), ("What should I do today?", "Act"), ("Show me overdue actions.", "Monitor"), ("Prioritize my actions.", "Decide"), ("Show me actions linked to opportunities.", "Act"),
          ("Show me actions linked to risks.", "Act")],
 additional=[("Which actions need approval?", "Act"), ("What happened after we acted?", "Monitor"), ("Create a follow-up task.", "Act"), ("Show me actions by owner.", "Analyze"), ("Show me completed actions this week.", "Monitor"),
             ("Which actions had the most impact?", "Analyze"), ("Show me actions waiting on me.", "Act"), ("Escalate this action.", "Act"), ("Show me the approval history.", "Investigate"), ("Cancel an action I proposed.", "Act")],
 follow=["Which actions need approval?", "What happened after we acted?", "Show me actions by owner."],
 outcomes=["Governed actions: policy check, human approval, execution and outcome tracking"], personas={"sales_director": ["Show me actions waiting on me."]}),
dict(id="rfp", name="RFP Response", skill="rfp-response-composer", intent="rfp", slash="rfp", domain="Sales",
 description="Respond to RFPs and questionnaires from approved content.",
 primary=[("Analyze this RFP.", "Analyze"), ("Build an RFP response strategy.", "Prepare"), ("Identify the customer's evaluation criteria.", "Discover"), ("Identify our gaps in this RFP.", "Investigate"),
          ("Analyze our competitive positioning for this RFP.", "Analyze"), ("Draft the RFP response structure.", "Act")],
 additional=[("Build the compliance matrix.", "Prepare"), ("What can't we answer in this RFP?", "Investigate"), ("Draft answers from approved content.", "Act"), ("Which questions need an expert?", "Act"), ("Flag risky requirements in this RFP.", "Investigate"),
             ("Tailor answers to the customer's win themes.", "Prepare"), ("Respond to this security questionnaire.", "Act"), ("Summarize the RFP for the bid team.", "Prepare"), ("Should we bid on this RFP?", "Decide"), ("Show me unusual contract terms.", "Investigate")],
 follow=["Build the compliance matrix.", "Which questions need an expert?", "Should we bid on this RFP?"],
 outcomes=["A compliance matrix, grounded draft answers and flagged gaps with expert routing"], personas={}),
dict(id="solution", name="Solution Design", skill="solution-architecture", intent="solution", slash="solution", aliases=["architecture"], domain="Operations",
 description="Translate business problems into solutions and architectures.",
 primary=[("Design a solution for this opportunity.", "Prepare"), ("Create the target architecture.", "Prepare"), ("Map business requirements to capabilities.", "Analyze"), ("Identify integration requirements.", "Investigate"),
          ("Identify architecture and technical risks.", "Investigate"), ("Create an executive solution overview.", "Prepare")],
 additional=[("Design the target state.", "Prepare"), ("Identify integration dependencies.", "Investigate"), ("Build an implementation roadmap.", "Prepare"), ("What delivery model fits this solution?", "Decide"), ("What is the value case for this solution?", "Analyze"),
             ("Map requirements to our approved capabilities.", "Analyze"), ("Show me reference solutions we've delivered.", "Discover"), ("What would this solution cost to deliver?", "Analyze"), ("Compare solution options.", "Decide"), ("Create an executive architecture view.", "Prepare")],
 follow=["Build an implementation roadmap.", "What is the value case for this solution?", "Compare solution options."],
 outcomes=["Problem → capability → solution → architecture → delivery → value → risks → roadmap"], personas={"it_leader": ["Identify integration dependencies.", "Create the target architecture."]}),
dict(id="winloss", name="Win/Loss", skill="win-loss-intelligence", intent="win_loss", slash="winloss", domain="Sales",
 description="Learn why deals are won and lost.",
 primary=[("Analyze why we won.", "Investigate"), ("Analyze why we lost.", "Investigate"), ("Identify recurring loss patterns.", "Analyze"), ("Show competitive win/loss patterns.", "Analyze"), ("Find lessons from historical deals.", "Discover"),
          ("Recommend changes based on past outcomes.", "Decide")],
 additional=[("What do our wins have in common?", "Analyze"), ("Who are we losing to?", "Analyze"), ("Show me the loss-reason Pareto.", "Analyze"), ("How does discount affect win rate?", "Investigate"), ("Show me win rate by segment.", "Analyze"),
             ("Which loss reasons are increasing?", "Monitor"), ("What should we change in how we sell?", "Decide"), ("Run a win/loss review for last quarter.", "Prepare"), ("Compare win rates by deal size.", "Analyze"), ("Which patterns are statistically reliable?", "Investigate")],
 follow=["What should we change in how we sell?", "Show competitive win/loss patterns.", "Build my sales forecast."],
 outcomes=["Reliable win/loss patterns fed back into forecasting, pricing and deal strategy"], personas={"cro": ["What should we change in how we sell?"]}),
dict(id="knowledge", name="Knowledge", skill="knowledge-intelligence", intent="knowledge", slash="knowledge", domain="Operations",
 description="Find the authoritative answer in company knowledge.",
 primary=[("Find the relevant knowledge for [[{account}|this account]].", "Discover"), ("Search our previous work.", "Discover"), ("Find similar situations we've handled.", "Investigate"), ("Find lessons from similar past work.", "Discover"),
          ("Find supporting evidence for this claim.", "Investigate"), ("Summarize the relevant knowledge.", "Prepare")],
 additional=[("What's our current policy on this?", "Discover"), ("Find the latest version of this document.", "Discover"), ("Which document is authoritative?", "Investigate"), ("Do our documents contradict each other?", "Investigate"), ("What did we commit in the contract?", "Investigate"),
             ("Find proposals for similar opportunities.", "Discover"), ("Find case studies for this industry.", "Discover"), ("Show me stale content to review.", "Monitor"), ("What is our approved position on this topic?", "Discover"), ("Find our current pricing guidance.", "Discover")],
 follow=["Which document is authoritative?", "Find case studies for this industry.", "Do our documents contradict each other?"],
 outcomes=["The current, authoritative answer with source and version, conflicts flagged"], personas={}),
dict(id="memory", name="Business Memory", skill="business-memory", intent="memory_recall", slash="memory", domain="Operations",
 description="What we already know, decided and learned.",
 primary=[("What do we already know about [[{account}|this account]]?", "Discover"), ("Show me the history[[ of {account}]].", "Discover"), ("What did we learn previously?", "Discover"), ("What decisions have we made?", "Discover"),
          ("Show me previous outcomes.", "Investigate"), ("Update the business memory.", "Act")],
 additional=[("What did we predict, and what happened?", "Investigate"), ("What changed since last time?", "Monitor"), ("Show me decisions still in force.", "Discover"), ("What assumptions did we record?", "Investigate"), ("Show me past recommendations and their outcomes.", "Investigate"),
             ("Forget an outdated fact.", "Act"), ("Correct a fact in memory.", "Act"), ("Show me how sure we are about each fact.", "Investigate"), ("When was this information last updated?", "Monitor"), ("Show me what we know about this competitor.", "Discover")],
 follow=["What did we predict, and what happened?", "Show me decisions still in force.", "Correct a fact in memory."],
 outcomes=["Temporal facts, decisions, predictions and outcomes with sources"], personas={}),
dict(id="digital-twin", name="Customer Digital Twin", skill="customer-digital-twin", intent="twin", slash="digital-twin", domain="Customers",
 description="The customer's current state, history, forecast and what-ifs.",
 primary=[("Show me the current customer state[[ of {account}]].", "Discover"), ("What's changed in the customer twin?", "Monitor"), ("Show me historical trends[[ for {account}]].", "Analyze"), ("Show me the customer forecast.", "Analyze"),
          ("Run a what-if scenario on this customer.", "Decide"), ("Show me the target state[[ for {account}]].", "Prepare")],
 additional=[("Give me the full picture on [[{account}|this customer]].", "Discover"), ("Why did this account change?", "Investigate"), ("What's likely next for this customer?", "Analyze"), ("Show me the account 360.", "Discover"),
             ("Compare the current state with the target.", "Analyze"), ("Set a target for this account.", "Act"), ("Show me the financial state of the customer.", "Analyze"), ("Show me the competitive state of the customer.", "Analyze"),
             ("Show me the relationship state.", "Analyze"), ("Show me every snapshot of this account.", "Investigate")],
 follow=["Compare the current state with the target.", "Run a what-if scenario on this customer.", "Build my complete [[{account} ]]account strategy."],
 outcomes=["Eight state domains across historical, current, forecast, what-if and target"], personas={}),
dict(id="data", name="Data Analysis", skill="data-intelligence", intent="data_analysis", slash="data", domain="Operations",
 description="Analyze any dataset and make it decision-ready.",
 primary=[("Analyze this dataset.", "Analyze"), ("What patterns do you see in this data?", "Analyze"), ("Find anomalies in this data.", "Investigate"), ("Explain the key drivers in this data.", "Investigate"),
          ("Build an analytical summary of this data.", "Prepare"), ("Create a decision-ready view of this data.", "Decide")],
 additional=[("Is this data reliable?", "Investigate"), ("Find duplicates in our CRM.", "Investigate"), ("Reconcile CRM and ERP data.", "Act"), ("What's in this file?", "Discover"), ("Clean up our CRM data.", "Act"),
             ("Which fields are missing or stale?", "Investigate"), ("Map this data to accounts and opportunities.", "Prepare"), ("Profile the data quality.", "Analyze"), ("Show me trends in this data.", "Analyze"), ("Compare these two datasets.", "Analyze")],
 follow=["Is this data reliable?", "Explain the key drivers in this data.", "Show me the state of the business."],
 outcomes=["Schema, quality profile, KPIs, trends, drivers and recommendations"], personas={"it_leader": ["Is our data reliable?", "Reconcile CRM and ERP data."]}),
dict(id="dashboard", name="Dashboards", skill="dashboard-intelligence", intent="dashboard", slash="dashboard", domain="Dashboards",
 description="Open the right dashboard for your role and account.",
 primary=[("Show me my growth command center[[ for {account}]].", "Discover"), ("Show me what changed on the dashboard.", "Monitor"), ("Build the dashboard I need for [[{account}|this account]].", "Prepare"),
          ("Show me opportunities and risks on the dashboard.", "Analyze"), ("Create an executive dashboard.", "Prepare"), ("Analyze this dashboard.", "Analyze")],
 additional=[("Show me the financial story dashboard.", "Analyze"), ("Show me competitive threads on the dashboard.", "Monitor"), ("Show me marketing signals on the dashboard.", "Monitor"), ("Compare this account with others.", "Analyze"),
             ("Run a scenario from the dashboard.", "Decide"), ("Drill into this metric.", "Investigate"), ("Open the CFO view.", "Discover"), ("Open the account executive view.", "Discover"), ("Refresh the dashboard.", "Act"), ("Show me the dashboard evidence.", "Investigate")],
 follow=["Show me what changed on the dashboard.", "Drill into this metric.", "Run a scenario from the dashboard."],
 outcomes=["A persona-adapted, evidence-linked command center artifact"], personas={"ceo": ["Create an executive dashboard."], "investor": ["Open the investor view."], "cfo": ["Open the CFO view."]}),
dict(id="watch", name="Business Watch", skill="business-watch", intent="watch", slash="watch", domain="Operations",
 description="Get alerted when something that matters changes.",
 primary=[("Alert me when a big deal slips.", "Monitor"), ("Watch my strategic accounts for risk.", "Monitor"), ("Tell me if a competitor enters my accounts.", "Monitor"), ("Alert me when coverage drops below target.", "Monitor"),
          ("Notify me if an executive sponsor leaves.", "Monitor"), ("Show me what my watches found.", "Monitor")],
 additional=[("Watch [[{account}|this account]] for health changes.", "Monitor"), ("Alert me when renewal risk rises.", "Monitor"), ("Tell me if expansion probability jumps.", "Monitor"), ("Watch revenue at risk.", "Monitor"),
             ("Show me all my active watches.", "Discover"), ("Turn off a watch.", "Act"), ("Watch customer sentiment.", "Monitor"), ("Alert me to forecast changes.", "Monitor"), ("Tell me if margin falls below target.", "Monitor"),
             ("Explain why this watch fired.", "Investigate")],
 follow=["Explain why this watch fired.", "Show me all my active watches.", "What needs my attention today?"],
 outcomes=["Conditions evaluated on each refresh; each firing investigated with a recommended action"], personas={"cro": ["Alert me when a big deal slips."]}),
dict(id="outreach", name="Prospect Research & Outreach", skill="account-intel-outreach", intent="research", slash="outreach", domain="Sales",
 description="Research a target account and draft first-touch outreach.",
 primary=[("Research [[{account}|this prospect]] for me.", "Discover"), ("Why this account, why now, why us?", "Analyze"), ("Draft outreach to the CIO.", "Act"), ("Find a reason to reach out[[ to {account}]].", "Discover"),
          ("Prioritize my target accounts.", "Decide"), ("Personalize my outreach sequence.", "Act")],
 additional=[("Draft a LinkedIn message to the CFO.", "Act"), ("Which customer stories fit this prospect?", "Discover"), ("What changed at this prospect recently?", "Monitor"), ("Build an account point of view.", "Prepare"),
             ("Who should I contact first?", "Decide"), ("Find recent news about this prospect.", "Discover"), ("Draft a follow-up after no reply.", "Act"), ("Which prospects are showing intent?", "Monitor"), ("Map the prospect's buying group.", "Discover"),
             ("Summarize this prospect in five lines.", "Prepare")],
 follow=["Draft outreach to the CIO.", "Map the prospect's buying group.", "Prep me for my next sales call."],
 outcomes=["A cited point of view and persona-specific first-touch drafts (sent only after approval)"], personas={"ae": ["Research [[{account}|this prospect]] for me."], "marketing_leader": ["Which prospects are showing intent?"]}),
dict(id="admin", name="Platform Administration", skill="platform-admin", intent="admin", slash="admin", domain="Operations", admin_only=True,
 description="Platform health, usage and governance (administrators only).",
 primary=[("Show me platform health.", "Monitor"), ("Show me active capabilities.", "Discover"), ("Show me assistant performance.", "Analyze"), ("Show me errors.", "Investigate"), ("Show me usage.", "Analyze"), ("Show me governance events.", "Monitor")],
 additional=[("Show me what a request cost.", "Analyze"), ("Show me recent traces.", "Investigate"), ("Run the regression tests.", "Act"), ("Show me policy violations.", "Investigate"), ("Disable an underperforming capability.", "Act"),
             ("Show me evaluation scores.", "Analyze"), ("Show me tenant isolation checks.", "Investigate"), ("Show me approval turnaround times.", "Analyze"), ("Show me data-source freshness.", "Monitor"), ("Show me cost by team.", "Analyze")],
 follow=["Show me errors.", "Show me evaluation scores.", "Run the regression tests."],
 outcomes=["Registry, traces, cost, evaluations and governance events for administrators"], personas={}),
]
# Domain hubs (slash commands that open a menu of capabilities) and the global home.
HUBS = {
 "growth": {"name": "Growth Intelligence", "description": "Start here: what would you like to do?", "capabilities": None},
 "sales": {"name": "Sales", "description": "Accounts, opportunities, deals, forecast, meetings and outreach.", "capabilities": ["account", "opportunities", "deal", "forecast", "meeting", "followup", "relationships", "outreach", "rfp", "winloss", "pricing"]},
}
INTERNAL = {"business-orchestrator": "routes every request (not invoked directly by users)", "artifact-dashboard-intelligence": "renders dashboards built by Dashboards",
            "business-context-discovery": "runs automatically at the start of every analysis"}
EXPLORE = ["Growth", "Sales", "Accounts", "Customers", "Competition", "Marketing", "Finance", "Market", "Meetings", "Decisions", "Dashboards", "Operations"]
CATEGORIES = ["Discover", "Analyze", "Investigate", "Decide", "Prepare", "Act", "Monitor"]
PERSONAS = {
 "investor": ("Investor", [("executive", 0), ("financial", 0), ("market", 1), ("competition", 2), ("scenario", 0), ("executive", 3)]),
 "ceo": ("CEO", [("executive", 0), ("signals", 0), ("opportunities", 0), ("executive", 3), ("decision", 0), ("briefing", 0)]),
 "cfo": ("CFO", [("financial", 0), ("forecast", 5), ("scenario", 0), ("pricing", 3), ("renewals", 0), ("decision", 5)]),
 "coo": ("COO", [("executive", 0), ("actions", 0), ("customer-growth", 3), ("scenario", 4), ("data", 2), ("watch", 1)]),
 "growth_ops": ("Growth Operations Head", [("signals", 0), ("marketing", 3), ("forecast", 2), ("opportunities", 1), ("dashboard", 0), ("briefing", 0)]),
 "cro": ("CRO", [("forecast", 1), ("forecast", 0), ("opportunities", 0), ("competition", 2), ("winloss", 2), ("dashboard", 0)]),
 "sales_head": ("Sales Head", [("forecast", 0), ("account", 0), ("opportunities", 0), ("competition", 1), ("briefing", 0), ("account", 1)]),
 "sales_director": ("Sales Director", [("forecast", 3), ("deal", 1), ("relationships", 1), ("threads", 1), ("actions", 0), ("meeting", 0)]),
 "ae": ("Account Executive", [("meeting", 0), ("account", 0), ("opportunities", 0), ("deal", 5), ("relationships", 5), ("briefing", 2)]),
 "marketing_leader": ("Marketing Leader", [("marketing", 3), ("marketing", 1), ("marketing", 4), ("signals", 0), ("competition", 5), ("opportunities", 0)]),
 "cs_leader": ("Customer Success Leader", [("renewals", 0), ("customer-growth", 0), ("customer-growth", 2), ("relationships", 1), ("digital-twin", 0), ("actions", 0)]),
 "operations_leader": ("Operations Leader", [("bi", 3), ("actions", 2), ("data", 2), ("scenario", 0), ("watch", 1), ("executive", 3)]),
 "it_leader": ("IT Leader", [("solution", 1), ("solution", 3), ("data", 0), ("knowledge", 1), ("solution", 4), ("market", 4)]),
}
GLOBAL_HOME = [("account", 0), ("opportunities", 0), ("meeting", 0), ("forecast", 0), ("account", 1), ("briefing", 0)]
